### ISSUE TITLE
Change User-Agent header from uploading as the insights-operator to cost-mgmt-operator

### ISSUE THREAD

**Issue by abaiken** [project-koku/korekuta-operator#16]
Right now in order to use token authentication for uploading to production we have to masquerade as the `insights-operator`. However @chambridge put out a PR to allow our operator to utilize the uhc-proxy-flow. As soon as this [PR](https://github.com/RedHatInsights/uhc-auth-proxy/pull/5/files) is merged, we need to change our token auth `User-Agent` header to contain `cost-mgmt-operator` instead of `insights-operator`.

The line that needs to change will be [here](https://github.com/project-koku/korekuta-operator/blob/master/roles/collect/tasks/main.yml#L277).

- [ ] Verify that the header is updated to contain `cost-mgmt-operator`
- [ ] Verify that uploading to insights via token auth still works

**Comment by lcouzens** [comment]
Verified
