### ISSUE TITLE
Create cost operator to setup Metering custom resources

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta-operator#3]
## User Story
As a customer, I want a simplified setup experience for collecting OpenShift cost metering data, so that the barrier to utilize cost management is lower.

## Impacts
- Operator
- Docs

## Assumptions
- OpenShift 4.2+ cluster
- Operator Metering has been installed and configured

## Implementation Details:
Create a basic Ansible based operator utilizing the operator framework (https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md). Create a role which creates the CRDs currently created by Korekuta (https://github.com/project-koku/korekuta/tree/master/roles/setup/files).

## Acceptance Criteria:
- [ ] Verify that the operator installs on a OpenShift 4.2+ cluster
- [ ] Verify that the CRDs are created within OpenShift in the installed namespace

**Comment by lcouzens** [comment]
Verified
