### ISSUE TITLE
Improve development flow on operator/cleanup 

### ISSUE THREAD

**Issue by abaiken** [project-koku/korekuta-operator#34]
## Description 
Currently our Operator instructions for development are to edit existing files that are tracked using git. The problem with this is that someone might accidentally check in the changes that they are testing. Instead we should update the documentation & flow to copy the CRDS that we need to edit to a folder that is git-ignored and edit the files there. 

## Verify
- [ ] Documentation is updated to not edit checked in items 
- [ ] Development works as expected

**Comment by lcouzens** [comment]
Verified
