### ISSUE TITLE
Configure cost operator to upload cost reports

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta-operator#5]
## User Story
As a customer, I want the OpenShift metrics to be uploaded to cloud.redhat.com, so that I can utilize this data with the OpenShift cost management feature.

## Impacts
- Operator
- Docs

## Assumptions
- OpenShift 4.2+ cluster
- Operator Metering has been installed and configured
- Custom resources have been successfully created and reports had time (an hour to run)
- Metrics are being collected and properly packaged

## Implementation Details
- Default to cloud.redhat.com but allow override for preprod environments (only works if they are behind the firewall, but worth having the capability from the start); operator config
- Add support to the operator to configure token (details below); preferred method (default if cred type not specified in operator config). Specify secret name in operator config.
- Add support to the operator to configure basic authentication credentials to communicate with the Ingress service. Specify secret name in operator config (username, password).
- Install root CA chain as mounted volume (see below).
- Call the Ingress service with the upload payload utilizing the credentials.

Model after insights-operator:
in the `openshift-insights` project there are the following pieces:
ConfigMap - *trusted-ca-bundle* (we should be able to copy this and install it with our operator)
Secret - *operator-token-frtzk* (obviously not alway this name) contains a token value.

trusted-ca-bundle is used to enable sslVerify when making the [POST to ingress](https://github.com/openshift/insights-operator/blob/27768551b735b1cd6a4c9363db8b71a2a2b5c471/pkg/insights/insightsclient/insightsclient.go#L73-L89).

You can see the code we want to mirror with Ansible [here](https://github.com/openshift/insights-operator/blob/27768551b735b1cd6a4c9363db8b71a2a2b5c471/pkg/insights/insightsclient/insightsclient.go#L116-L212).

We setup the authentication to [support basic auth or bearer token](https://github.com/openshift/insights-operator/blob/915a77d65a9862fa2411fac208e5b477e0f57924/pkg/authorizer/clusterauthorizer/clusterauthorizer.go#L25-L46).

## Acceptance Criteria
- [ ] Verify that the payload is sent to the Ingress service and routed to cost management with the existing format.

**Comment by lcouzens** [comment]
Verified
