### ISSUE TITLE
Install Operator Metering as a dependency

### ISSUE THREAD

**Issue by adberglund** [project-koku/korekuta-operator#6]
## User Story
As a customer, I want the installation of the cost operator to also install the dependencies it requires, so that minimal steps are required to enable the cost operator to collect and report metrics.

We decided to have the customer configure the meteringconfig because there are so many different ways to set it up. 

## Impacts
- Operator
- Docs

## Assumptions
- OpenShift 4.2+ cluster
- Operator Metering has not been installed and configured

## Implementation Details
- Operators have a mechanism for defining dependency resolution (https://github.com/operator-framework/olm-book/blob/master/docs/operator-dependencies-and-requirements.md), these steps need to be followed to enable the installation of operator-metering.

## Acceptance Criteria
- [ ] Verify that operator-metering is installed when the cost operator is installed

**Comment by lcouzens** [comment]
Verified
